version: '3'
services:
    main-remix:
        image: main-remix:latest
        container_name: 'main-remix'
        hostname: main-remix
        environment:
            NODE_ENV: production
        build:
            context: .
            dockerfile: Dockerfile
        networks:
          - net
        ports:
            - '3000:3000'
        restart: always
networks:
  net:
    driver: bridge